### ISSUE TITLE
[Spike]: CFBindingController should not assume any concrete AppWorkload implementation

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1949]
### Background

Currently the CFServiceBinding controller is reconciling `cfservicebindings` to `servicebindings.servicebinding.io` resources with a [`statefulset` workload](https://github.com/cloudfoundry/korifi/blob/d155777c455da0b14ee8d2359e66dcf95c34e94f/controllers/controllers/services/cfservicebinding_controller.go#L213-L221). This leaks app workload specific implementation detais into the binding controller and prevents the development of alternative app workload implementations (e.g. one backed by `deployments`).

Furthermore, the servicebinding.io is causing apps to restart upon binding a service as the statefulset spec changes. This is unexpected behaviour from the CF perspective

Lastly, the servicebinding.io does not seem to be well maintained anymore. It is vendoring an old controller runtime version and this is preventing us from bumping controller runtime ourselves

### Dev Notes:

- Instead of depending on the servicebinding.io controller, let's do the projection ourselves. This way we will fix the problems above and still have the bindings mounted to the app containers in the desired format

### TODO

- [x] Remove servicebinding.io from tests/vendir.yml
- [x] Revert back to using `controllerutil.CreateOrPatch` in AppWorkloadController
- [x] Implement the projection of the mount secrets
- [x] ~Address [TODO](https://github.com/cloudfoundry/korifi/blob/3ed1e89b069ebf03ac1c70915843ffb189447fe6/controllers/controllers/workloads/apps/controller.go#L144) in app controller~ we hace decided not to pass the references to the binding secrets as the env builder needs the binding itself, alongside the instance, to build the VCAP_SERVICES env var
- [x] (Optional) Fill in empty test: https://github.com/cloudfoundry/korifi/blob/3ed1e89b069ebf03ac1c70915843ffb189447fe6/controllers/controllers/workloads/processes/controller_test.go#L401
- [x] Remove servicebinding.io from go.mod
- [x] Check whether we are backwards compatible with 0.14
- [x] Remove all references of servicebinding.io from docs
- [x] Write a new ADR documenting the decision to drop the servicebinding.io controller

**Comment by danail-branekov** [comment]
We are observing statefulset pods being restarted several times while an app is being deleted. We believe that the reason for this bahviour is the way servicebinding.io projects its binding into the statefulset.
While an app is being deleted and finalized, the app controller [deletes](https://github.com/cloudfoundry/korifi/blob/1af41fa9d4c2fd31b8029bb3b02801927623cf23/controllers/controllers/workloads/apps/controller.go#L378-L384) all the bindings to the app. That causes servicebinding.io to alter the statefulset spec and that causes pods restart.

We have tried to disable the service instance finalization bit when finalizing the app, indeed - app deletion became much faster.

If we managed to solve this issue, we may also solve app deletion being slow as well.

Idea: Can we build the volumes and volume mounts to be projected ourselves in the app/process controller, so that the runner can put them in the pod spec? This way we do not need to install servicebinding.io and we will not have our workload resources inexpectedly modified by a controller that does not own them. This means there will be no undesired restarts. We believe that projecting the volume mounts will not be very hard, as it is only a [small fraction](https://github.com/servicebinding/spec?tab=readme-ov-file#workload-projection) of the servicebinding.io spec.
