### ISSUE TITLE
Delete redundant authorization tests from e2e suite

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#2519]
There are certain [negative e2e tests](https://github.com/cloudfoundry/korifi/blob/a47fc282da476646fa9b8f29f75c1415e4989b12/tests/e2e/routes_test.go#L71-L86) in korifi testing role permissions. As we are using the real generated role definitions in our envtest [repository integration tests](https://github.com/cloudfoundry/korifi/blob/a47fc282da476646fa9b8f29f75c1415e4989b12/api/repositories/repositories_suite_test.go#L96-L102). and the repositories are our boundary with k8s, these files should already be covered there. The e2e authorization tests are redundant, but expensive (an e2e test run take around 12-13m). Therefore we should only put positive tests there that test the wiring in the `main.go`, as this wiring is different from the test wiring that takes place in the suite.

Let's revise all e2e tests and delete each redundant authorization test, making sure there is no hole in the repo integration tests.
```[tasklist]
### Tasks
- [ ] Remove e2e tests that test authorisation
- [ ] Use a cfadmin client in all tests and remove org/space user roles setup
- [ ] Check whether tests that use a client for a service account make sense, if not - delete them. See this [slack thread](https://cloudfoundry.slack.com/archives/C0297673ASK/p1690366748263079)
- [ ] Create users needed for tests on the fly, i.e. do not rely on users already existing and being provided to tests via env variables.
- [ ] Cleanup scripts and make targets by removing setting up users/certificates/tokens/env vars prior running the e2e tests
- [ ] Cleanup CI tasks/scripts by removing setting up users/certificates/tokens/env vars prior running the e2e tests
```
