### ISSUE TITLE
[Explore] cf push --docker

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2741]
Explore what needs to be done to be able to push apps with the docker lifecycle

```[tasklist]
### Tasks
- [x] Come up with a proposal document on how to support that
- [ ] Discuss and agree on open questions with the community
- [ ] Create stories to implement the feature
```

Proposal document:
https://docs.google.com/document/d/1vJLBL1f_ebZm7YWJ9iiNa3DHhrhTOUIyBg1DzIpyuDA/edit#heading=h.9w70n3ykktw2
