### ISSUE TITLE
As a kubectl Korifi user I want to see the containerPorts property on the pod spec set to the route destination ports

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2840]
### Background

As of today the containerPorts in the pod spec is not set at all

#### Default port 8080
**Given** I cf push an app
**When** I look at the resulting pod spec
**Then** I see that containerPorts is set to `[8080]`

**Given** I insert a new destination with a custom port by sending the following request

```
curl "https://api.example.org/v3/routes/[guid]/destinations" \
  -X POST \
  -H "Authorization: bearer [token]"
  -H "Content-type: application/json"
  -d '{
    "destinations": [
      {
        "app": {
          "guid": "1cb006ee-fb05-47e1-b541-c34179ddc446"
        }
      },
      {
        "app": {
          "guid": "01856e12-8ee8-11e9-98a5-bb397dbc818f",
          "process": {
            "type": "api"
          }
        },
        "port": 9000,
        "protocol": "http1"
      }
    ]
  }'
```

**When** I look at the resulting pod spec
**Then** I see that containerPorts is set to `[8080, 9000]`

#### Use custom port (not 8080)
**Given**
* I create an app: `cf create-app app1`
* I create a route with port `6666`

```
curl "https://api.example.org/v3/routes" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/json" \
  -d '{
    "host": "a-hostname",
    "path": "/some_path",
    "port": 6666,
    "relationships": {
      "domain": {
        "data": { "guid": "domain-guid" }
      },
      "space": {
        "data": { "guid": "space-guid" }
      }
    },
    "metadata": {
      "labels": { "key": "value" },
      "annotations": { "note": "detailed information"}
    }
  }'
```
* I map the route to the app
* I create a package/build for the app, set the droplet on that app and start the app
**When** I look at the resulting pod spec
**Then** I see that containerPorts is set to `[6666]`

### Dev notes
At the moment, defaulting to port 8080 is carried out in both the route handler and the manifest applier. It is probably a good idea to move that defaulting into the route repository.

### Tasks
- [ ] Create chore to move the app process type defaulting logic to the repository (or maybe move all defaulting to a webhook in the controller layer)
- [ ] API Shim as well as all contollers other than the cf route controller should get the route destinations from the cfroute status and not from the spec
- [ ] Route reconciler to read ports from the droplet and update contour/service objects accordingly
- [ ] Make sure ports are propagated to the containerPorts field in the pod spec
