### ISSUE TITLE
As a Korifi user I want to be able to expose the Korifi API using any Gateway API compatible networker

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#3052]
### Background

As the Gateway API is now =[v1.0.0]() we should abstract the Contour newtworker away from Korifi, so that users can deploy Korifi with their own newtworker (i.e Istio).

### Acceptance

**GIVEN** that I have a Gateway API compatible networker installed on my k8s cluster
**AND** I have configured a gatewayclass
**WHEN** I deploy Korifi passing my gatewayclass name as a helm value
**THEN** I can access the Korifi API as usual

### Dev notes

At this point app routes are still serviced by the Contour specific CRDS such as httpproxies, but the request comes in via the Gateway API gateway.

### Tasks

- [ ] Add a `networking.gatewayClass` value to the Korifi helm chart
- [ ] Replace the Contour api ingress with an equivalent Gateway API gateway
- [ ] Update the docs with instructions on how to setup Contour to run with Gateway API support
